function(custom_target_sanitize_options target)
    if(RAW_SANITIZE)
        if(RAW_SANITIZE_ADDRESS)
            if(WIN)
            else()
                target_compile_options(${target} PUBLIC -fsanitize=address)
                target_link_options(${target} PUBLIC -fsanitize=address)
            endif()
        endif()
        if(RAW_SANITIZE_UNDEFINED)
            if(WIN)
            else()
                target_compile_options(${target} PUBLIC -fsanitize=undefined)
                target_link_options(${target} PUBLIC -fsanitize=undefined)
            endif()
        endif()
    endif()
endfunction()

function(custom_target_debug_options target)
    if(RAW_DEBUG_INFO)
        if(MSVC)
            # target_compile_options(${target} PRIVATE /Z7)
            target_link_options(${target} PRIVATE /DEBUG)
            target_link_options(${target} PRIVATE /OPT:NOICF)
            target_link_options(${target} PRIVATE /OPT:REF)
        else()
            target_compile_options(${target} PRIVATE -g)
            target_compile_options(${target} PRIVATE -frecord-gcc-switches)
        endif()
    endif()
endfunction()

function(custom_target_executable_properties)
endfunction()

